import express from 'express';
import bodyParser from 'body-parser';
import cors from 'cors';
import { RegisterRoutes } from './routes/routes'; // Generated by tsoa
import swaggerUi from 'swagger-ui-express';
import * as swaggerDocument from './swagger/swagger.json'; // Generated by tsoa

const app = express();

app.use(cors());
app.use(bodyParser.json());

RegisterRoutes(app);

app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`Server is running on port ${PORT}`);
});
